### ISSUE TITLE
Two quick suggestions!

### ISSUE THREAD

**Issue by pkmuldoon** [linearza/analyze-files#1]
A) You may want to not process binaries files. Even if they match the `--include-extensions` glob.
b) An option to follow symbolic links or not to avoid endless processing loops.

It also attempts to write to ./dist. If that directory doesn't exist, it will fail to write the output.

Looks good, though!

**Comment by linearza** [comment]
Thanks @pkmuldoon! Only saw this issue now. I've updated the code to handle optional `dist` dir and to exclude binaries in all cases: https://github.com/linearza/analyze-files/commit/d71664e809b7b93c7a5d2bc5821a777646f11b6b
